version: "3"

services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ToBeIT#2017
      MYSQL_USER: web
      MYSQL_PASSWORD: ToBeIT#2017
  tobeit:
    image: tobeit
    depends_on:
      - mysql
    ports:
      - "80:80"
      - "443:443"
